#!/usr/bin/env bash
#
# Deploy CampusNav V2 to production:
#   frontend (SPA)  -> Vercel
#   backend (API)   -> Render web service + managed Postgres (render.yaml Blueprint)
#
# Prerequisites (one-time, interactive — required from the account owner):
#   npm i -g vercel && vercel login        # browser auth
#   npm i -g @render/cli && render login   # browser auth (+ create an API key at
#                                          # https://dashboard.render.com/api if needed)
#
# Usage:
#   ./deploy.sh <BACKEND_URL> <FRONTEND_URL>
#   e.g. ./deploy.sh https://campusnav-api.onrender.com https://campusnav-v2-dhanush.vercel.app
#
# What it does (never prints secrets):
#   1. Preflight: both CLIs installed + authenticated.
#   2. Frontend: link project, set VITE_API_URL (Production), deploy --prod.
#   3. Backend:  render blueprint launch --sync (env: JWT_SECRET auto-generated,
#                DATABASE_URL injected, CORS_ORIGINS overridden with <FRONTEND_URL>).
#   4. Prints the live URLs + /health check command.
set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "usage: $0 <BACKEND_URL> <FRONTEND_URL>" >&2
  exit 64
fi
BACKEND_URL="$1"
FRONTEND_URL="$2"

for tool in vercel render; do
  if ! command -v "$tool" >/dev/null; then
    if [[ "$tool" == "vercel" ]]; then
      echo "missing vercel — run: npm i -g vercel" >&2
    else
      echo "missing render — run: npm i -g @render/cli" >&2
    fi
    exit 64
  fi
done

echo "== preflight auth =="
vercel whoami >/dev/null 2>&1 || { echo "run: vercel login" >&2; exit 70; }
render whoami >/dev/null 2>&1 || { echo "run: render login (see https://render.com/docs/cli)" >&2; exit 70; }

echo "== frontend: Vercel =="
vercel link --yes --project campusnav-v2 >/dev/null
echo "$BACKEND_URL" | vercel env add VITE_API_URL production
vercel --prod

echo "== backend: Render Blueprint (API + Postgres) =="
# CORS override; JWT_SECRET is generated by the platform (generateValue).
render blueprint launch --sync --env "CORS_ORIGINS=$FRONTEND_URL" campusnav-v2-api

echo
echo "== done =="
echo "frontend: $FRONTEND_URL"
echo "backend:  $BACKEND_URL"
echo "health:   $BACKEND_URL/health"
echo "next: verify with the smoke checklist in DEPLOYMENT-REPORT.md §Q"